-- Industrial Heater Coil Calculator - Supabase restore
-- Run this in the SQL Editor of a fresh Supabase project.

begin;

drop table if exists public.kanthal_d_wires cascade;
drop table if exists public.nichrome_wires cascade;

create table public.kanthal_d_wires (
  id bigint generated by default as identity primary key,
  swg integer not null,
  thickness numeric not null,
  ohm numeric not null,
  minw integer not null,
  maxw integer not null
);

create table public.nichrome_wires (
  id bigint generated by default as identity primary key,
  swg integer not null,
  thickness double precision not null,
  ohm double precision not null,
  minw integer not null,
  maxw integer not null,
  updated_at timestamp without time zone default now()
);

insert into public.kanthal_d_wires (id, swg, thickness, ohm, minw, maxw) values
  (1, 20, 0.914, 1.668, 1900, 2099),
  (2, 21, 0.813, 2.103, 1600, 1899),
  (3, 22, 0.711, 2.720, 1300, 1590),
  (4, 23, 0.610, 3.691, 1200, 1299),
  (5, 24, 0.559, 4.550, 900, 1199),
  (6, 26, 0.508, 6.755, 800, 899),
  (7, 28, 0.376, 9.840, 600, 799),
  (8, 30, 0.315, 14.417, 400, 599),
  (9, 32, 0.274, 17.830, 300, 399);

insert into public.nichrome_wires (id, swg, thickness, ohm, minw, maxw, updated_at) values
  (1, 22, 0.711, 2.76, 1300, 1599, '2026-01-02 17:46:21.420545'),
  (2, 23, 0.61, 3.728, 1200, 1299, '2026-01-02 17:46:21.420545'),
  (3, 24, 0.559, 4.536, 900, 1199, '2026-01-02 17:46:21.420545'),
  (4, 25, 0.508, 5.31, 850, 1049, '2026-01-02 17:46:21.420545'),
  (5, 26, 0.457, 6.802, 800, 899, '2026-01-02 17:46:21.420545'),
  (6, 28, 0.376, 9.793, 600, 799, '2026-01-02 17:46:21.420545'),
  (7, 30, 0.305, 13.744, 400, 599, '2026-01-02 17:46:21.420545'),
  (8, 32, 0.274, 18.32, 300, 399, '2026-01-02 17:46:21.420545'),
  (9, 32, 0.274, 18.32, 300, 399, '2026-01-02 17:46:21.420545'),
  (10, 34, 0.234, 25.9, 250, 299, '2026-01-02 17:46:21.420545'),
  (11, 35, 0.213, 31.596, 225, 274, '2026-01-02 17:46:21.420545'),
  (12, 36, 0.193, 36.06, 200, 249, '2026-01-02 17:46:21.420545'),
  (13, 36, 0.193, 36.06, 200, 249, '2026-01-02 17:46:21.420545'),
  (14, 37, 0.173, 45.82, 175, 199, '2026-01-02 17:46:21.420545'),
  (15, 38, 0.152, 62.88, 150, 199, '2026-01-02 17:46:21.420545'),
  (16, 38, 0.152, 59.408, 150, 199, '2026-01-02 17:46:21.420545'),
  (17, 39, 0.132, 78.4, 133, 174, '2026-01-02 17:46:21.420545'),
  (18, 40, 0.122, 93.2, 125, 149, '2026-01-02 17:46:21.420545'),
  (19, 40, 0.122, 94, 125, 149, '2026-01-02 17:46:21.420545'),
  (20, 42, 0.102, 139.2, 100, 124, '2026-01-02 17:46:21.420545'),
  (21, 42, 0.102, 139.2, 100, 124, '2026-01-02 17:46:21.420545'),
  (22, 44, 0.081, 214.66, 10, 99, '2026-01-02 17:46:21.420545'),
  (23, 44, 0.081, 214.66, 10, 99, '2026-01-02 17:46:21.420545');

select setval(pg_get_serial_sequence('public.kanthal_d_wires', 'id'), (select max(id) from public.kanthal_d_wires), true);
select setval(pg_get_serial_sequence('public.nichrome_wires', 'id'), (select max(id) from public.nichrome_wires), true);

alter table public.kanthal_d_wires enable row level security;
alter table public.nichrome_wires enable row level security;

create policy "public read kanthal wires"
  on public.kanthal_d_wires for select
  to anon, authenticated
  using (true);

create policy "public insert kanthal wires"
  on public.kanthal_d_wires for insert
  to anon, authenticated
  with check (true);

create policy "public update kanthal wires"
  on public.kanthal_d_wires for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "public read nichrome wires"
  on public.nichrome_wires for select
  to anon, authenticated
  using (true);

create policy "public insert nichrome wires"
  on public.nichrome_wires for insert
  to anon, authenticated
  with check (true);

create policy "public update nichrome wires"
  on public.nichrome_wires for update
  to anon, authenticated
  using (true)
  with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update on public.kanthal_d_wires to anon, authenticated;
grant select, insert, update on public.nichrome_wires to anon, authenticated;
grant all on public.kanthal_d_wires to service_role;
grant all on public.nichrome_wires to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

commit;
